# Generated by Django 4.1.2 on 2022-10-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.TextField()),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
    ]
